- name: restart nginx
  systemd:
    name: nginx
    state: restarted

- name: reload nginx
  systemd:
    name: nginx
    state: reloaded

- name: start nginx
  systemd:
    name: nginx
    state: started

- name: stop nginx
  systemd:
    name: nginx
    state: stopped