---
# Common handlers
- name: restart ssh
  systemd:
    name: ssh
    state: restarted

- name: restart sudo
  command: /bin/true
  # Sudo doesn't need restart, just validation

- name: reload ufw
  ufw:
    state: reloaded

- name: restart ntp
  systemd:
    name: ntp
    state: restarted

- name: restart rsyslog
  systemd:
    name: rsyslog
    state: restarted